# Configuration of script for hyperparameter search with optuna and mlflow
experiment_name: 'Experiment 13 node feaures ones'
random_state: 17


hydra:
  job:
    chdir: True
  sweeper:
    sampler:
      seed: ${random_state}
    direction: minimize
    study_name: skip_gcn_hp
    storage: null
    n_trials: 12
    n_jobs: 12
    params:
      #training.batch_size: int(interval(80, 200))
      training.embedding_size: int(interval(3, 15))

defaults:
  - data: config
  - training: config
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  # Config from this file override the values of configs from the Defaults List
  - _self_

debug: True

mlflow:
  tracking_uri: 'sqlite:///${hydra:runtime.cwd}/../mlflow/mlruns.db'