# Parameters for training process
embedding_size: 8
batch_size: 10

learning_rate: 0.01
weight_decay: 5e-4

max_epoch: 1000

stoping:
  # Number of epochs to wait of decreasing of test loss before early stop
  patience: 50
  verbose: true
  delta: 0.0001
  path: '${hydra:runtime.output_dir}/hp_checkpoint.pt'
