# Parameters for training process
embedding_size: 5
learning_rate: 0.001
weight_decay: 1e-5

max_epoch: 1000

stoping:
  # Number of epochs to wait of decreasing of test loss before early stop
  patience: 300
  verbose: true
  delta: 0.001
  path: '${hydra:runtime.output_dir}/hp_checkpoint.pt'
